// ─── KOLD OS · M2 — Catálogo canónico de reglas de planeación (v1) ───────────
// Cada regla declara QUÉ incumplimiento evidencia, sobre qué entidad, con qué
// numerador/denominador del contrato del auditor, umbral, evidencia, área
// responsable y acción operativa recomendada. NINGUNA regla corrige nada:
// auto_fix = false SIEMPRE (M2 observa, no corrige).
//
// Tipos de evaluación (threshold.kind):
//   · zero      → 0 = GREEN; >0 = severidad de la regla (high→RED, medium→AMBER)
//   · min_pct   → pct >= green_at = GREEN; >= amber_at = AMBER; menor = RED
//   · max_pct   → pct <= green_at = GREEN; <= amber_at = AMBER; mayor = RED
//   · manual    → v1 sin datos en el contrato ⇒ NOT_EVALUABLE (gris, honesto)
//
// Umbrales 90/70 de cobertura: heredados del semáforo honesto de Route
// Intelligence (decisión D-A). El resto son defaults v1 PENDIENTES de
// ratificación (ver docs/m2/M2_RULE_CATALOG.md §umbrales).

export const M2_CATALOG_VERSION = 'kold.tower.m2.rules/1'

export const M2_CATEGORIES = Object.freeze([
  { key: 'territorio', label: 'Territorio', order: 1 },
  { key: 'solver', label: 'Solver', order: 2 },
  { key: 'vehiculo_capacidad', label: 'Vehículo y capacidad', order: 3 },
  { key: 'carga_handoff', label: 'Carga y handoff', order: 4 },
  { key: 'snapshots_forecast', label: 'Snapshots y forecast', order: 5 },
  { key: 'resultado_real', label: 'Resultado real', order: 6 },
])

export const M2_RESPONSIBLE_AREAS = Object.freeze({
  territorio: 'Operaciones / Administración de sucursal',
  solver: 'Planeación / Sistemas',
  vehiculo_capacidad: 'Operaciones / Flota',
  carga_handoff: 'Almacén / Jefe de ruta',
  snapshots_forecast: 'Planeación / Comercial / Datos',
  resultado_real: 'Operación de campo / Cierre de ruta',
})

const rule = (def) => Object.freeze({
  auto_fix: false,
  responsible_area: M2_RESPONSIBLE_AREAS[def.category],
  ...def,
})

export const M2_RULES = Object.freeze([
  // ── A · TERRITORIO ─────────────────────────────────────────────────────────
  rule({
    code: 'M2-A-01',
    category: 'territorio',
    name: 'Plan sin territorio',
    description: 'Planes diarios sin polígono ni subpolígono de planeación asignado: la ruta no está anclada a un territorio.',
    severity: 'high',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: 'territory_load_handoff_metrics',
    numerator: 'missing_territory_count',
    denominator: 'plan_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['missing_territory_count', 'plan_count'],
    expected_rule: 'Todo plan diario debe tener planning_polygon_id o planning_subpolygon_id.',
    recommended_action: 'Asignar territorio en el plan semanal antes de publicar; revisar catálogo de polígonos de la sucursal.',
  }),
  rule({
    code: 'M2-A-02',
    category: 'territorio',
    name: 'Territorio inválido',
    description: 'Planes que referencian un territorio inexistente o mal formado.',
    severity: 'high',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: null,
    numerator: null,
    denominator: null,
    threshold: { kind: 'manual', reason: 'El contrato v1 del auditor no expone validez del territorio.' },
    evidence_fields: [],
    expected_rule: 'Toda referencia de territorio debe resolver a un polígono existente.',
    recommended_action: 'Requiere extensión v1.1 del contrato (detalle por registro).',
  }),
  rule({
    code: 'M2-A-03',
    category: 'territorio',
    name: 'Territorio inactivo',
    description: 'Planes que referencian un territorio dado de baja.',
    severity: 'medium',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: null,
    numerator: null,
    denominator: null,
    threshold: { kind: 'manual', reason: 'El contrato v1 del auditor no expone estado activo del territorio.' },
    evidence_fields: [],
    expected_rule: 'Los planes solo deben usar territorios activos.',
    recommended_action: 'Requiere extensión v1.1 del contrato (detalle por registro).',
  }),

  // ── B · SOLVER ─────────────────────────────────────────────────────────────
  rule({
    code: 'M2-B-01',
    category: 'solver',
    name: 'Plan sin evidencia del solver',
    description: 'Planes diarios sin registro de ejecución del optimizador externo (external_solver_last_run_at vacío).',
    severity: 'high',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: 'solver_evidence_metrics',
    numerator: 'derived:plans_without_solver_evidence',
    denominator: 'derived:plan_universe',
    threshold: { kind: 'zero' },
    evidence_fields: ['solver_evidence_count', 'plan_count', 'solver_status'],
    expected_rule: 'Todo plan publicado debe conservar evidencia de la corrida del solver.',
    recommended_action: 'Ejecutar el optimizador antes de publicar; si se planeó manual, registrarlo explícitamente.',
  }),
  rule({
    code: 'M2-B-02',
    category: 'solver',
    name: 'Distancia por fuente de respaldo',
    description: 'Planes cuya distancia proviene de fallback/manual y no del solver.',
    severity: 'medium',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: 'solver_evidence_metrics',
    numerator: 'derived:fallback_distance_plans',
    denominator: 'derived:plan_universe',
    threshold: { kind: 'zero' },
    evidence_fields: ['distance_source', 'plan_count'],
    expected_rule: 'La fuente de distancia esperada es el solver externo.',
    recommended_action: 'Revisar disponibilidad del servicio route-optimizer y credenciales del conector.',
  }),
  rule({
    code: 'M2-B-03',
    category: 'solver',
    name: 'Ejecución del solver desactualizada',
    description: 'La corrida más reciente del solver es más vieja que el margen operativo (7 días) respecto al corte.',
    severity: 'medium',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: 'solver_evidence_metrics',
    numerator: 'derived:solver_age_days',
    denominator: null,
    threshold: { kind: 'max_age_days', green_at: 7 },
    evidence_fields: ['newest_solver_run_at'],
    expected_rule: 'Debe existir al menos una corrida del solver en los últimos 7 días.',
    recommended_action: 'Verificar cron/disparo del optimizador y el flag gf_route_optimizer_external.enabled.',
  }),

  // ── C · VEHÍCULO Y CAPACIDAD ───────────────────────────────────────────────
  rule({
    code: 'M2-C-01',
    category: 'vehiculo_capacidad',
    name: 'Plan sin vehículo',
    description: 'Planes diarios sin vehículo asignado.',
    severity: 'high',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: 'capacity_metrics',
    numerator: 'missing_vehicle_count',
    denominator: 'plan_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['missing_vehicle_count', 'plan_count'],
    expected_rule: 'Todo plan diario debe tener vehicle_id asignado.',
    recommended_action: 'Asignar vehículo desde el plan semanal; revisar disponibilidad de flota de la sucursal.',
  }),
  rule({
    code: 'M2-C-02',
    category: 'vehiculo_capacidad',
    name: 'Plan sin capacidad',
    description: 'Planes cuyo vehículo no declara capacidad (x_capacity_kg <= 0 o sin vehículo).',
    severity: 'high',
    entity_type: 'route_plan',
    source_model: 'fleet.vehicle',
    query_id: 'capacity_metrics',
    numerator: 'missing_capacity_count',
    denominator: 'plan_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['missing_capacity_count', 'plan_count'],
    expected_rule: 'Todo vehículo planificado debe declarar capacidad en kg.',
    recommended_action: 'Capturar x_capacity_kg en la ficha del vehículo (Flota).',
  }),
  rule({
    code: 'M2-C-03',
    category: 'vehiculo_capacidad',
    name: 'Plan diario con sobrecapacidad',
    description: 'Planes diarios cuya demanda excede la capacidad del vehículo (route_overcapacity).',
    severity: 'high',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: 'capacity_metrics',
    numerator: 'overcapacity_count',
    denominator: 'plan_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['overcapacity_count', 'plan_count', 'split_count', 'reload_count'],
    expected_rule: 'La demanda asignada no debe exceder la capacidad; el exceso se resuelve con split/reload.',
    recommended_action: 'Redistribuir demanda (split/reload) o asignar vehículo de mayor capacidad.',
  }),
  rule({
    code: 'M2-C-04',
    category: 'vehiculo_capacidad',
    name: 'Línea semanal con sobrecapacidad',
    description: 'Líneas del plan semanal con demanda por encima de la capacidad planificada.',
    severity: 'high',
    entity_type: 'weekly_plan_line',
    source_model: 'gf.route.weekly.plan.line',
    query_id: 'weekly_plan_metrics',
    numerator: 'sum:overcapacity_line_count',
    denominator: 'sum:line_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['overcapacity_line_count', 'line_count', 'state'],
    expected_rule: 'Ninguna línea semanal debe planearse por encima de la capacidad.',
    recommended_action: 'Rebalancear la semana antes de publicar (dividir carga o sumar vehículo).',
  }),
  rule({
    code: 'M2-C-05',
    category: 'vehiculo_capacidad',
    name: 'Vehículo inactivo o fuera de compañía',
    description: 'Planes que usan vehículos dados de baja o de otra compañía.',
    severity: 'medium',
    entity_type: 'route_plan',
    source_model: 'fleet.vehicle',
    query_id: null,
    numerator: null,
    denominator: null,
    threshold: { kind: 'manual', reason: 'El contrato v1 no expone estado/compañía del vehículo.' },
    evidence_fields: [],
    expected_rule: 'Los planes solo deben usar vehículos activos de su compañía.',
    recommended_action: 'Requiere extensión v1.1 del contrato (detalle por registro).',
  }),

  // ── D · CARGA Y HANDOFF ────────────────────────────────────────────────────
  rule({
    code: 'M2-D-01',
    category: 'carga_handoff',
    name: 'Plan publicado sin carga',
    description: 'Planes en estado published sin ningún picking de carga vinculado (handoff a almacén no ocurrió).',
    severity: 'high',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: 'territory_load_handoff_metrics',
    numerator: 'published_without_load_count',
    denominator: 'published_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['published_without_load_count', 'published_count'],
    expected_rule: 'Todo plan publicado debe generar su carga (stock.picking) antes de operar.',
    recommended_action: 'Generar la carga desde el plan publicado; revisar el flujo plan→almacén de la sucursal.',
  }),
  rule({
    code: 'M2-D-02',
    category: 'carga_handoff',
    name: 'Plan diario sin snapshot de demanda',
    description: 'Planes diarios sin demand_snapshot_id: no hay evidencia de la demanda usada para planear.',
    severity: 'high',
    entity_type: 'route_plan',
    source_model: 'gf.route.plan',
    query_id: 'handoff_metrics',
    numerator: 'plan_missing_snapshot_count',
    denominator: 'daily_plan_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['plan_missing_snapshot_count', 'daily_plan_count'],
    expected_rule: 'Todo plan diario debe anclarse a un snapshot de demanda.',
    recommended_action: 'Generar snapshot antes de derivar el plan diario; revisar el generador de snapshots.',
  }),
  rule({
    code: 'M2-D-03',
    category: 'carga_handoff',
    name: 'Plan diario sin stops',
    description: 'Planes diarios sin ninguna parada (gf.route.stop): plan vacío u orfandad del handoff.',
    severity: 'high',
    entity_type: 'route_plan',
    source_model: 'gf.route.stop',
    query_id: 'handoff_metrics',
    numerator: 'plan_without_stops_count',
    denominator: 'daily_plan_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['plan_without_stops_count', 'daily_plan_count', 'stop_count'],
    expected_rule: 'Todo plan diario debe tener al menos una parada.',
    recommended_action: 'Regenerar stops desde la línea semanal o cancelar el plan vacío (manual, con criterio).',
  }),
  rule({
    code: 'M2-D-04',
    category: 'carga_handoff',
    name: 'Línea semanal publicada sin almacén',
    description: 'Líneas semanales publicadas sin almacén de despacho (planned_warehouse_dispatch_id).',
    severity: 'high',
    entity_type: 'weekly_plan_line',
    source_model: 'gf.route.weekly.plan.line',
    query_id: 'weekly_plan_metrics',
    numerator: 'state:published:missing_warehouse_count',
    denominator: 'state:published:line_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['missing_warehouse_count', 'line_count', 'state'],
    expected_rule: 'Una línea publicada debe declarar el almacén que despacha.',
    recommended_action: 'Completar almacén de despacho antes de publicar la semana.',
  }),
  rule({
    code: 'M2-D-05',
    category: 'carga_handoff',
    name: 'Línea semanal sin snapshot',
    description: 'Líneas semanales sin snapshot de demanda vinculado.',
    severity: 'medium',
    entity_type: 'weekly_plan_line',
    source_model: 'gf.route.weekly.plan.line',
    query_id: 'weekly_plan_metrics',
    numerator: 'sum:missing_snapshot_count',
    denominator: 'sum:line_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['missing_snapshot_count', 'line_count'],
    expected_rule: 'Toda línea semanal debe anclarse a un snapshot de demanda.',
    recommended_action: 'Generar snapshot semanal antes de armar líneas.',
  }),

  // ── E · SNAPSHOTS Y FORECAST ───────────────────────────────────────────────
  rule({
    code: 'M2-E-01',
    category: 'snapshots_forecast',
    name: 'Cobertura de forecast insuficiente',
    description: 'La cobertura promedio de forecast en snapshots está por debajo del umbral operativo.',
    severity: 'high',
    entity_type: 'demand_snapshot',
    source_model: 'gf.route.demand.snapshot',
    query_id: 'snapshot_metrics',
    numerator: 'weighted:coverage_avg',
    denominator: null,
    threshold: { kind: 'min_pct', green_at: 90, amber_at: 70 }, // D-A (RI semáforo honesto)
    evidence_fields: ['coverage_avg', 'snapshot_count'],
    expected_rule: 'Cobertura promedio >= 90% (GREEN) / >= 70% (AMBER).',
    recommended_action: 'Aumentar cobertura del forecast (catálogo cliente-producto) antes de confiar en el plan.',
  }),
  rule({
    code: 'M2-E-02',
    category: 'snapshots_forecast',
    name: 'Confianza de snapshot baja',
    description: 'El score de confianza promedio de los snapshots está por debajo del umbral.',
    severity: 'high',
    entity_type: 'demand_snapshot',
    source_model: 'gf.route.demand.snapshot',
    query_id: 'snapshot_metrics',
    numerator: 'weighted:confidence_avg',
    denominator: null,
    threshold: { kind: 'min_score', green_at: 0.85, amber_at: 0.7 }, // default v1, pendiente ratificación
    evidence_fields: ['confidence_avg', 'snapshot_count'],
    expected_rule: 'Confianza promedio >= 0.85 (GREEN) / >= 0.70 (AMBER).',
    recommended_action: 'Revisar calidad de insumos del snapshot (historia, catálogos, fallback).',
  }),
  rule({
    code: 'M2-E-03',
    category: 'snapshots_forecast',
    name: 'Líneas de snapshot en fallback',
    description: 'Líneas de snapshot resueltas por mecanismo de respaldo (sin forecast directo).',
    severity: 'medium',
    entity_type: 'demand_snapshot',
    source_model: 'gf.route.demand.snapshot',
    query_id: 'snapshot_metrics',
    numerator: 'sum:fallback_count',
    denominator: 'sum:line_count',
    threshold: { kind: 'zero' },
    evidence_fields: ['fallback_count', 'line_count'],
    expected_rule: 'Las líneas deben resolverse con forecast directo, no fallback.',
    recommended_action: 'Cerrar huecos de forecast para los pares cliente-producto en fallback.',
  }),
  rule({
    code: 'M2-E-04',
    category: 'snapshots_forecast',
    name: 'Warnings de snapshot',
    description: 'Advertencias emitidas durante la generación de snapshots.',
    severity: 'medium',
    entity_type: 'demand_snapshot',
    source_model: 'gf.route.demand.snapshot',
    query_id: 'snapshot_metrics',
    numerator: 'sum:warning_count',
    denominator: null,
    threshold: { kind: 'zero' },
    evidence_fields: ['warning_count'],
    expected_rule: 'La generación de snapshots no debe emitir warnings.',
    recommended_action: 'Revisar el log de generación y atender las causas de warning.',
  }),
  rule({
    code: 'M2-E-05',
    category: 'snapshots_forecast',
    name: 'Snapshot desactualizado',
    description: 'El snapshot más reciente es más viejo que el margen operativo respecto al corte de la auditoría.',
    severity: 'medium',
    entity_type: 'demand_snapshot',
    source_model: 'gf.route.demand.snapshot',
    query_id: 'snapshot_metrics',
    numerator: 'derived:snapshot_age_days',
    denominator: null,
    threshold: { kind: 'max_age_days', green_at: 3 },
    evidence_fields: ['newest_target_date'],
    expected_rule: 'Debe existir un snapshot con target_date en los últimos 3 días.',
    recommended_action: 'Verificar generación diaria de snapshots.',
  }),

  // ── F · RESULTADO REAL ─────────────────────────────────────────────────────
  rule({
    code: 'M2-F-01',
    category: 'resultado_real',
    name: 'Cobertura de resultado real insuficiente',
    description: 'Proporción de historia de demanda con actual_kg capturado: sin real no hay Plan vs Real.',
    severity: 'high',
    entity_type: 'demand_history',
    source_model: 'kold.demand.history',
    query_id: 'history_metrics',
    numerator: 'actual_kg_count',
    denominator: 'row_count',
    threshold: { kind: 'min_pct', green_at: 80, amber_at: 50 }, // default v1, pendiente ratificación
    evidence_fields: ['actual_kg_count', 'row_count'],
    expected_rule: 'actual_kg capturado en >= 80% de la historia (GREEN) / >= 50% (AMBER).',
    recommended_action: 'Cerrar el ciclo de captura de venta real por ruta (cierre de ruta alimenta actual_kg).',
  }),
  rule({
    code: 'M2-F-02',
    category: 'resultado_real',
    name: 'Forecast sin marcar final',
    description: 'Proporción de forecast disponible marcado como final.',
    severity: 'medium',
    entity_type: 'demand_forecast',
    source_model: 'kold.demand.forecast',
    query_id: 'forecast_metrics',
    numerator: 'final_count',
    denominator: 'row_count',
    threshold: { kind: 'min_pct', green_at: 95, amber_at: 80 },
    evidence_fields: ['final_count', 'row_count'],
    expected_rule: 'El >= 95% del forecast de la ventana debe estar en estado final.',
    recommended_action: 'Cerrar el pipeline de finalización del forecast.',
  }),
  rule({
    code: 'M2-F-03',
    category: 'resultado_real',
    name: 'Días sin forecast en la ventana',
    description: 'Días de la ventana auditada sin ningún forecast disponible.',
    severity: 'medium',
    entity_type: 'demand_forecast',
    source_model: 'kold.demand.forecast',
    query_id: 'forecast_metrics',
    numerator: 'derived:uncovered_days',
    denominator: 'derived:window_days',
    threshold: { kind: 'zero' },
    evidence_fields: ['covered_days'],
    expected_rule: 'Todos los días de la ventana deben tener forecast disponible.',
    recommended_action: 'Verificar el generador de forecast diario.',
  }),
])

export function getRuleByCode(code) {
  return M2_RULES.find((r) => r.code === code) || null
}

export function rulesByCategory(categoryKey) {
  return M2_RULES.filter((r) => r.category === categoryKey)
}

export function categoryLabel(categoryKey) {
  const cat = M2_CATEGORIES.find((c) => c.key === categoryKey)
  return cat ? cat.label : categoryKey
}
